import assert from 'node:assert/strict';
import { etapePersonnelle, limiteLecture, etapeDePreparation, estEtapeLisible } from '../src/lib/parcoursDomain';
import type { ParcoursGroup } from '../src/lib/types';
import { reinitialiserStockage, doitReinitialiser } from '../src/lib/reinitialisation';
const groupe = (currentStep: number) => ({ currentStep } as ParcoursGroup);
assert.equal(etapePersonnelle([]), 1);
assert.equal(etapePersonnelle([2, 3]), 1, 'une fiche future ne débloque pas les prérequis');
assert.equal(etapePersonnelle([1]), 2);
assert.equal(etapePersonnelle([1, 3]), 2);
assert.equal(etapePersonnelle(Array.from({ length: 20 }, (_, i) => i + 1)), 20);
assert.equal(limiteLecture(null, []), 1, 'mode personnel : fiche 2 fermée avant la fin de la 1');
assert.equal(limiteLecture(null, [1]), 2);
assert.equal(limiteLecture(groupe(1), [1]), 1, 'la préparation personnelle ne remplace pas la clôture de groupe');
assert.equal(limiteLecture(groupe(2), [1]), 2);
assert.equal(limiteLecture(groupe(2), []), 1, 'un membre doit aussi terminer ses prérequis');
assert.equal(etapeDePreparation(groupe(1)), 1);
assert.equal(estEtapeLisible(groupe(1), 2), false);
assert.equal(estEtapeLisible(groupe(1), 0), false);
const donnees = new Map([['lf.groups', 'anciens groupes'], ['lesfondements_prog_old', 'ancienne progression'], ['autre.application', 'conserver']]);
const stockage = { get length() { return donnees.size; }, key: (i: number) => [...donnees.keys()][i] ?? null,
 getItem: (k: string) => donnees.get(k) ?? null, setItem: (k: string, v: string) => { donnees.set(k, v); }, removeItem: (k: string) => { donnees.delete(k); }, clear: () => donnees.clear() };
assert.equal(doitReinitialiser(stockage), true);
reinitialiserStockage(stockage);
assert.equal(donnees.has('lf.groups'), false);
assert.equal(donnees.has('lesfondements_prog_old'), false);
assert.equal(donnees.get('autre.application'), 'conserver');
assert.equal(doitReinitialiser(stockage), false);
donnees.set('lesfondements_prog_new', 'nouvelle progression');
reinitialiserStockage(stockage);
assert.equal(donnees.get('lesfondements_prog_new'), 'nouvelle progression', 'le reset ne se répète pas');
console.log('✓ Accès séquentiel personnel et groupe ; ancienne session locale effacée une seule fois.');
